spring.application.name=veiculos

spring.datasource.url=jdbc:mysql://localhost:3306/veiculos
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Mailtrap Email Sending (Transactional)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=b2b99d842a4dda
spring.mail.password=1fd22a9bb73c92
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# From must match a verified sender/domain in Mailtrap Email Sending
app.mail.from=no-reply@seu-dominio-verificado.com


# Configurações de logging: define o arquivo de saída (logs/veiculos.log),
# o nível padrão global (INFO) e um nível mais detalhado (DEBUG) apenas para o pacote da aplicação para facilitar a depuração sem gerar excesso de logs de bibliotecas externas.
logging.file.name=logs/veiculos.log
logging.level.root=INFO
logging.level.com.veiculos=DEBUG